### ISSUE TITLE
Batch Size Problem

### ISSUE THREAD

**Issue by MiladGhorbaniG** [junming259/UWStereoNet_disparity#1]
Hi @junming259 , Thanks for the code resource. I'm training my own dataset (image size : 512*512, train : 3349, val : 886)  using 2 GPUs (each one 7.6 G RAM). I have a problem that I can only train the network only with BatchSize = 1 and higher batch sizes raise OOM error. How to train with higher batch size?

**Comment by junming259** [comment]
I guess a feasible way is either resize your inputs to smaller scale (like 256*256) or crop them. Getting GPUs with more memory is also a common solution.

**Comment by MiladGhorbaniG** [comment]
Thanks for your suggestions.
