### ISSUE TITLE
Checkpoints not available

### ISSUE THREAD

**Issue by jeffin07** [junming259/UWStereoNet_disparity#2]
Hai @junming259 I was trying to infer.py, no information on checkpoints in the readme

**Comment by junming259** [comment]
During inference, the exported model is used. So you may need to run export_model.py before doing inference. And the checkpoints are used here.

**Comment by jeffin07** [comment]
@junming259 Okay. I was trying to infer without training with my own data. I was trying this method with the official trained checkpoints, before training with my own data I just want to check the performance on the official checkpoints

**Comment by junming259** [comment]
I didn't include pretrained checkpoint in the repo, and I don't think I will do that in the future. Training will not be hard, just give it a try:)
