### ISSUE TITLE
Maximum Disparity

### ISSUE THREAD

**Issue by MiladGhorbaniG** [junming259/UWStereoNet_disparity#3]
Hi @junming259, I trained the model on my 16-bit data (I normalize it between -1 and 1) When I run the inference.py, the output range is like below (28269 - 28865)
![image](https://user-images.githubusercontent.com/47980221/91492600-2c739980-e8cb-11ea-899c-33fa82c51bda.png)
Is this range normal? I expected that its range be 0-192 as the maximum disparity is 192

However, the result is not satisfying. 
![image](https://user-images.githubusercontent.com/47980221/91495438-cb9a9000-e8cf-11ea-91fc-2c5b47c2026e.png)

Another question that I have is that when I change max_disparity (from 192 to 16), it raises the following error:

ValueError: Dimensions must be equal, but are 8 and 2 for 'build_graph/model/Initial/modual3D/shortcut3/Add' (op: 'Add') with input shapes: [1,8,32,32,64], [1,2,32,32,64].

**Comment by junming259** [comment]
1. The inputs I assume are png images with uint8. So make sure you modified the code in image_reader.py for your customized inputs. 

2. The output disparity is multiplied by 256 and saved in uint16 format, that's why you get results in large range. [check](https://github.com/junming259/UWStereoNet_disparity/blob/master/export_model.py#L72)

3. During the process, the cost volume tensor is downsampled and then upsampled three times. When the max_disparity is not set properly, the tensor size will not be consistent for a symmetric U-shape structure and it raises error when doing add operation.

**Comment by MiladGhorbaniG** [comment]
Thanks for the response. It's now more clear to me. I have changed the image_reader.py. My guess is that the reason is the skewness of my data as its statistics are like below:
red:           mean = 190   std = 105   min = 0   max = 2047
green:       mean = 252   std = 109   min = 0   max = 2047
blue:          mean = 235  std = 89     min = 0   max = 2047
I divide to 1024 and minus 1 for normalization. Its stats may change like below:
red:           mean = -0.81   std = 0.106   min = -1   max = 1
...
Can this make the model not to train well? 
My batch-size equals 1, may it be the cause of not training well?

**Comment by junming259** [comment]
I am sorry that I cannot give specific idea why your training was not good, since I don't know your dataset. Make sure your normalization step is correct in image_reader.py. At least for the dataset I used (Cityscapes, KITTI and some underwater dataset), the model will output decent results when batchsize is set to 1. How are the training results shown in tensorboard?

**Comment by MiladGhorbaniG** [comment]
My data is stereo satellite imagery taken by a satellite but in two different timestamps. Here is one of my data patches:
![image](https://user-images.githubusercontent.com/47980221/91618038-9e68e300-e99e-11ea-9c1e-8017a55a20a7.png)
I have changed the image_reader.py as:


def load_examples(dirs, size, dataset, batch_size):


    HEIGHT = size[0]
    WIDTH = size[1]
   
    if dirs[1] is not None:
        Examples = collections.namedtuple("Examples", "lefts, rights, count, batch_size")

        input_left_dir = glob.glob(os.path.join(dirs[0], '*.png'))
        input_right_dir = glob.glob(os.path.join(dirs[1], '*.png'))
        input_left_dir.sort()
        input_right_dir.sort()
        with tf.name_scope("load_images"):
            path_queue = tf.train.slice_input_producer([input_left_dir,
                                                        input_right_dir], shuffle=True)
            with tf.name_scope('read_left_image'):
                contents = tf.read_file(path_queue[0])
                left = tf.image.decode_png(contents, dtype=tf.uint16)
                left = tf.image.convert_image_dtype(left, dtype=tf.float32)
                # normalize image to [-1,1]
                left = preprocess(left)


            with tf.name_scope('read_right_image'):
                contents = tf.read_file(path_queue[1])
                right = tf.image.decode_png(contents, dtype=tf.uint16)
                right = tf.image.convert_image_dtype(right, dtype=tf.float32)
                right = preprocess(right)

            with tf.name_scope('random_crop_images'):
                total = tf.concat([left, right], axis=-1)
                # if dataset == 'cityscapes':
                #     total = tf.image.resize_images(total, [256, 256])
                cropped_total = tf.random_crop(total, [256, 256, 6])
                left, right = tf.split(cropped_total, [3, 3], axis=-1)
            left_batch, right_batch = tf.train.batch([left, right], batch_size=batch_size)

        return Examples(
                    lefts=left_batch,
                    rights=right_batch,
                    count=len(input_left_dir),
                    batch_size=batch_size)
def preprocess(img):

    img = 0.8*(img-tf.math.reduce_mean(img))/(tf.math.reduce_std(img)+0.00001)
    img = tf.clip_by_value(img, -1, 1)
    return img
if __name__ == "__main__":

    example = load_examples()

    lefts = example.lefts
    c = example.count

    init = tf.global_variables_initializer()

    with tf.Session() as sess:
        sess.run(init)
        s = sess.run(lefts)
        print(s.shape)
`
The loss is decreasing:
![image](https://user-images.githubusercontent.com/47980221/91638842-796c8280-ea27-11ea-94d2-c9d8d8030af0.png)

**Comment by junming259** [comment]
Your `preprocess(img)` function normalizes each input img. In your case, the same color value in two images will be likely different after `preprocess()`, which is not ideal for stereo matching. The output of `tf.image.convert_image_dtype` is within range [0,1). If it is the case, I will implement `preprocess()` as following:
```
def preprocess(img):
    img = img * 2 - 1
    return img
```
Double check the output of `preprocess()` is within [-0.5, 0.5).

**Comment by MiladGhorbaniG** [comment]
For me, the normalization (`img*64-1` : img is in range [0 2048/65536) = [0 1/32) ) resulted non satisfying (as of the first post). But then I've tested the new normalization ( `0.8*(img-tf.math.reduce_mean(img))/(tf.math.reduce_std(img)+0.00001)` ) which its result after 30k triaining seems to be more reasonable but now there is an issue that half of image is gray.
Left image:
![image](https://user-images.githubusercontent.com/47980221/91643126-ca8b6f00-ea45-11ea-8cf0-0691fd390086.png)
Right Disparity:
![image](https://user-images.githubusercontent.com/47980221/91643115-b6e00880-ea45-11ea-8506-76231729b2a4.png)
Left Disparity:
![image](https://user-images.githubusercontent.com/47980221/91643101-9a43d080-ea45-11ea-871f-31a2062727ba.png)

**Comment by junming259** [comment]
I still suspect that your current normalization will lead to error, because `tf.math.reduce_mean(img)`  and `tf.math.reduce_std(img)` are individually computed for each image. It will be better to do the normalization using the mean and std of the whole dataset. Besides, I guess that normalizing each color channel independently maybe better.
